### ISSUE TITLE
How do I get the random module to work?

### ISSUE THREAD

**Issue by jcarmbruster** [qpython-android/qpython#169]
I've installed Qpython3 on my android cellphone.

However, when I typed in "import random" in one program, and ran the program, the following error message appears:
Traceback (most recent call last):
   File "/storage/emulated/0/qpython/scripts3/.last_tmp.py", line 11,
in <module>
     import random.py
  File "/storage/emulated/0/qpython/scripts3/random.py", line 7, in <
module>
     random.randint(0,2)
AttributeError: 'module' object has no attribute 'randint'
1ǀuo_a183@tc_a32ewh1:/ $

What does this mean? And how can I get the random module to run properly?

Thanks,

J.C. (John Clifford) Armbruster

**Comment by benjaminfang** [comment]
try
dir(random)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by git-jr** [comment]
For me it works on version 2.6.0 this:
random import
print (random.randint (0,6))

https://github.com/qpython-android/qpython/releases/tag/v2.6.0
